fix: arm64 & macOS aarch64 gh-r selection
Signed-off-by: Vladislav Doster <mvdoster@gmail.com>

diff --git a/tests/_support/bootstrap b/tests/_support/bootstrap
--- a/tests/_support/bootstrap
+++ b/tests/_support/bootstrap
@@ -1,20 +1,32 @@
 #!/usr/bin/env zsh
 
 # Log functions [[[
-function error(){ print -P "%F{red}ZUNIT[ERROR]: $1%f" && return 1; }
-function info() { print -P "%F{blue}ZUNIT[INFO]%f: %F{cyan}$1%f"; }
-function warn() { print -P "%F{yellow}ZUNIT[WARN]: $1%f"; }
+function error(){ print -P "%F{red}[ERROR]%f: ${1}" && return 1; }
+function info() { print -P "%F{green}[INFO]%f:%F{cyan} ${1} %f"; }
+function warn() { print -P "%F{yellow}[WARN]%f: ${1}"; }
 # ]]]
 # Create Zunit test environment [[[
 GIT_REPO=$(git rev-parse --show-toplevel)
-typeset -gAH  ZINIT;
-ZINIT[HOME_DIR]="$GIT_REPO/tests/_support/zunit";    ZINIT[BIN_DIR]=$ZINIT[HOME_DIR]/zinit.git;
-ZINIT[COMPLETIONS_DIR]=$ZINIT[HOME_DIR]/completions; ZINIT[SNIPPETS_DIR]=$ZINIT[HOME_DIR]/snippets;
-ZINIT[ZCOMPDUMP_PATH]=$ZINIT[HOME_DIR]/zcompdump;    ZINIT[PLUGINS_DIR]=$ZINIT[HOME_DIR]/plugins;
+
+_mktemp_cmd='mktemp'
+if (( ${+commands[gmktemp]} )); then
+  _mktemp_cmd='gmktemp'
+fi
+TMP_ZUNIT=$(${_mktemp_cmd} --directory --tmpdir="${GIT_REPO}/tests/_support")
+if [[ ! -d ${TMP_ZUNIT} ]]; then
+  error "zunit temp dir not found"
+  exit 1
+fi
+
+typeset -gAH ZINIT;
+ZINIT[HOME_DIR]=${TMP_ZUNIT};
+ZINIT[BIN_DIR]=$ZINIT[HOME_DIR]/zinit.git;
+ZINIT[COMPLETIONS_DIR]=$ZINIT[HOME_DIR]/completions;
+ZINIT[PLUGINS_DIR]=$ZINIT[HOME_DIR]/plugins;
+ZINIT[SNIPPETS_DIR]=$ZINIT[HOME_DIR]/snippets;
+ZINIT[ZCOMPDUMP_PATH]=$ZINIT[HOME_DIR]/zcompdump;
 ZPFX=$ZINIT[HOME_DIR]/polaris;
 
-rm -rf $ZINIT[HOME_DIR]
-mkdir -p $ZINIT[HOME_DIR]
 git diff > $ZINIT[HOME_DIR]/unstaged.diff
 info 'creating test env' \
   && git clone \
@@ -23,7 +35,7 @@ info 'creating test env' \
       --no-hardlinks \
       --reference "$GIT_REPO" \
       "$GIT_REPO" \
-    "$GIT_REPO"/tests/_support/zunit/zinit.git \
+    "${TMP_ZUNIT}"/zinit.git \
   || error 'failed to create zinit copy for test env' \
   &&  [[ -s $ZINIT[HOME_DIR]/unstaged.diff ]] \
   && git -C $ZINIT[BIN_DIR] apply $ZINIT[HOME_DIR]/unstaged.diff \
